/**:
  ros__parameters:
    image_topic: "/kitti/camera/color/left/image_raw"   # Image topic to subscribe to
    depth_weights_file: "/weights/rt_monodepth_full.engine" # Path to depth estimation file
    camera_frame: "cam2_link"
    base_frame: "base_link"
    camera_image_height: 375
    camera_image_width: 1242
    fx: 721.5377
    fy: 721.5377
    cx: 607.1928
    cy: 185.2157

